# Generated by Django 6.0 on 2026-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="github_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
