# Generated by Django 6.0 on 2026-01-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_alter_repository_github_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("repository", "number")},
        ),
    ]
